<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_MikroRendah</name>
   <tag></tag>
   <elementGuidId>bd9e40b8-2eeb-49e4-8954-b5cd3541c130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Permohonan persyaratan dasar dengan kategori Mikro Rendah.&quot; and @type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-v-0-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87b72790-aead-432b-a55e-714bc49cab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-v-0-12</value>
      <webElementGuid>4b5806cd-34ca-4ce0-ba47-c3bee38fb757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b8dd9fd-d3f1-44ad-89fa-a1bdae6f5eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Permohonan persyaratan dasar dengan kategori Mikro Rendah.</value>
      <webElementGuid>cccddd06-1b9f-4bc4-adc9-7a0fc8e10101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2496ccb3-e74b-4d4d-8cab-def3aca4053b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>317c4a01-92a8-4fce-9583-64bbeb4ba1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-v-0-12&quot;)</value>
      <webElementGuid>ac7790cf-9d4e-4166-9ce4-4f4132f4620c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-v-0-12']</value>
      <webElementGuid>d5e77266-8454-4500-a4df-bea0f131902c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cdc504ea-d6f3-445b-a8ba-eaaadd01fce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-v-0-12' and @type = 'checkbox']</value>
      <webElementGuid>960159d8-be6a-4b87-b64d-9b07ed801284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
