<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Simpan Posisi Lokasi_v-list-item-title_2</name>
   <tag></tag>
   <elementGuidId>53becac8-d296-4b63-b112-356c442d5a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-v-0-38']/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08b133c1-afb2-4aef-9d97-6cb35d16c700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item-title</value>
      <webElementGuid>25f2b355-a9b5-44e1-8e9c-59955ad0ac3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lembang</value>
      <webElementGuid>32085c53-3c04-4d8c-b7e9-c7874ff1690a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-v-0-38&quot;)/div[@class=&quot;v-overlay__content v-autocomplete__content&quot;]/div[@class=&quot;v-list v-theme--OssRbaTheme v-list--density-default v-list--one-line&quot;]/div[@class=&quot;v-list-item v-list-item--link v-theme--OssRbaTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item-title&quot;]</value>
      <webElementGuid>6e67fe87-a6c1-408c-876e-4905738d9eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-v-0-38']/div/div/div[2]/div/div</value>
      <webElementGuid>14fa8f3d-435e-4ca3-9036-ef4b87ea6ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lembang']/parent::*</value>
      <webElementGuid>72bfdd3e-2183-471e-8e25-6cc0ff752404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>15ef0078-95b9-426d-a32d-6bbe39ce8384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lembang' or . = 'Lembang')]</value>
      <webElementGuid>26b1e1ef-d924-4a92-98ff-79fa841cfa67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
