<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDown_JenisLuasLahan</name>
   <tag></tag>
   <elementGuidId>55863af1-dfc9-414f-b406-274e1ad87345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[@role=&quot;button&quot; and @tabindex=&quot;-1&quot; and @title=&quot;Open&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi-chevron-down.mdi.v-icon.notranslate.v-theme--OssRbaTheme.v-icon--size-default.v-icon--clickable.v-autocomplete__menu-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>45330259-f447-4fed-86f0-a7b2c58ada0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi-chevron-down mdi v-icon notranslate v-theme--OssRbaTheme v-icon--size-default v-icon--clickable v-autocomplete__menu-icon</value>
      <webElementGuid>cb188f01-bbfe-4901-bba4-f155f115127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>714e6316-c878-46df-a710-776551a74b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6740328e-fb65-48fa-81b2-0aa2c04087f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0c9c7f06-9049-4a9c-bada-ad8a3fd76bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>97c69232-e375-4b51-8201-51913eb1e2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>d88758c9-b649-4400-bb67-13efe5783b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;v-overlay-container&quot;]/div[@class=&quot;v-overlay v-overlay--active v-theme--OssRbaTheme v-locale--is-ltr v-dialog&quot;]/div[@class=&quot;v-overlay__content&quot;]/div[@class=&quot;v-card v-theme--OssRbaTheme v-card--density-default v-card--variant-elevated oss-rounded h-[90vh] flex flex-col&quot;]/div[@class=&quot;flex-1 overflow-auto content-modal&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[1]/form[@class=&quot;v-form flex flex-col gap-4&quot;]/div[@class=&quot;grid grid-cols-1 gap-4&quot;]/div[@class=&quot;grid grid-cols-12 gap-2 items-end&quot;]/div[@class=&quot;col-span-2&quot;]/div[@class=&quot;v-input v-input--horizontal v-input--center-affix v-input--focused v-input--density-default v-theme--OssRbaTheme v-locale--is-ltr v-text-field v-autocomplete v-autocomplete--single v-autocomplete--active-menu col-span-2 size-lg outlined&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-field v-field--active v-field--appended v-field--center-affix v-field--dirty v-field--no-label v-field--variant-solo-filled v-theme--OssRbaTheme v-field--focused v-field--rounded v-locale--is-ltr&quot;]/div[@class=&quot;v-field__append-inner&quot;]/i[@class=&quot;mdi-chevron-down mdi v-icon notranslate v-theme--OssRbaTheme v-icon--size-default v-icon--clickable v-autocomplete__menu-icon&quot;]</value>
      <webElementGuid>452f3a6b-f42a-4445-b638-b20e5162d620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/i</value>
      <webElementGuid>eb22d936-4fc6-43b0-9e7b-e356b4b77d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Close']</value>
      <webElementGuid>1fde963c-71af-4bae-bc30-e19a790fdf99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
