<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Pos_input-v-0-49</name>
   <tag></tag>
   <elementGuidId>784194f0-9631-4d8f-9356-5f632e5c0804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-v-0-49']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef9d0fd3-b41d-4573-a76d-5aafeb75ce6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Pos</value>
      <webElementGuid>966517ca-1fa3-4573-8713-d53eac4c61c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4990418a-9684-42af-a7a7-72bde62b0c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adf74571-7b7a-4bcd-a9fb-2919f1cfac35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-49</value>
      <webElementGuid>04a5bedb-e0af-4843-bc6a-7d32e898b5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-v-0-49-messages</value>
      <webElementGuid>648f88e3-204e-44d1-ae3c-5191f864b77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-49&quot;)</value>
      <webElementGuid>08eabd21-d284-428d-bfd9-afd91cb18a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-v-0-49']</value>
      <webElementGuid>88ee237f-7ed2-44ff-a246-85d4021c8d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[4]/div/input</value>
      <webElementGuid>945e4c9a-5c4f-4de9-8d77-d1804d6df2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kode Pos' and @type = 'text' and @id = 'input-v-0-49']</value>
      <webElementGuid>dbe663cb-e176-4683-aee4-652a8a36d97c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
