<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provinsi_input-v-0-30</name>
   <tag></tag>
   <elementGuidId>673ab5f6-d401-4101-ba64-b077a2442430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-v-0-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eafaa9e6-cf8a-4405-9c82-63aeed0ef4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih provinsi</value>
      <webElementGuid>1dedb407-f070-45a7-a8f8-6ee5986af062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0cdc943d-fad1-4258-bf68-f5766d382049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ff6d5298-d942-41dc-95ef-5103bb3fbde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>082740b8-57cd-4ae1-a609-b280242b9bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-30</value>
      <webElementGuid>237bf6bb-f53e-44c6-b4ba-22373ac543eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-v-0-30-messages</value>
      <webElementGuid>63f4c69c-cb33-4dd2-8e6c-3378c331d2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60b214df-ca7d-4f06-9da9-68fd5e696416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-v-0-28</value>
      <webElementGuid>ff5f70af-3d6a-4abd-bd26-e4f1d12ef1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-30&quot;)</value>
      <webElementGuid>298f6536-d629-432e-9d9f-63dcb449e03e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-v-0-30']</value>
      <webElementGuid>9bf4b916-6f57-4d85-ac91-0c7ae7579acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>a26ab9f3-347d-4b9b-9980-27d179d58561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih provinsi' and @type = 'text' and @id = 'input-v-0-30']</value>
      <webElementGuid>9614aea2-b3f7-4970-8ed9-5068cb8a07f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
