<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KotaKabupaten_input-v-0-35</name>
   <tag></tag>
   <elementGuidId>1959f161-78c8-4d3b-a738-a14dabe3326d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-v-0-35']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9e48217-91a1-4d2c-ad0c-e8d9c3ba0538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a435cadc-0a3f-4e99-bbd0-2cb99d7346cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>31ef9765-28b0-4da3-b09a-8f1fc9166a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>487859e5-8454-45f7-9999-a558542fa97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-35</value>
      <webElementGuid>27c13b49-60b5-475b-b343-c34d70b8f710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-v-0-35-messages</value>
      <webElementGuid>cd96d04b-089f-44ec-80d2-f22a524b668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c138ca3d-2457-4a91-a247-ca97d94de6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-v-0-33</value>
      <webElementGuid>9e017331-1ee9-4a1f-9505-a7f07734d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-35&quot;)</value>
      <webElementGuid>83849134-947f-4b91-90fa-b9a6adcb66fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-v-0-35']</value>
      <webElementGuid>00ead98e-8208-4efb-981c-3480d90ab5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>bb7b3db3-116e-43ff-b3a6-8d87c95de0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-v-0-35']</value>
      <webElementGuid>c1d2a148-77fd-4053-a1a3-927d888d5d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
