<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Koordinat</name>
   <tag></tag>
   <elementGuidId>cb410292-6dbe-4f7c-b7fe-09cae056874a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;Klik pada peta untuk menentukan koordinat&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-61</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>055f4496-d5a1-47cd-ad2e-0c5e27385981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Klik pada peta untuk menentukan koordinat</value>
      <webElementGuid>3550da35-262d-447b-a149-98c023f62bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04235d34-901b-4025-9b6b-6df5e9939d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46f7941b-8ef0-4b2e-b906-b1d3ddf51d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-61</value>
      <webElementGuid>c13b22d7-88b0-495d-8c98-e27ce7dfac53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>((-6.204051163695767,106.81663513183595))</value>
      <webElementGuid>8019982b-1cc2-4d92-b758-0e7114e1a93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-61&quot;)</value>
      <webElementGuid>fa2057e6-c30c-490e-a1e9-b78d6ca37f9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-v-0-61']</value>
      <webElementGuid>0d160f3e-e9c5-4be7-a41d-33d9c2453dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>76dc522e-38ce-4f4c-b812-df9872e31ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Klik pada peta untuk menentukan koordinat' and @type = 'text' and @id = 'input-v-0-61']</value>
      <webElementGuid>8cea8b1f-5923-4568-a208-58924fb2097c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
