<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LuasLahan</name>
   <tag></tag>
   <elementGuidId>d832e6e3-ad19-47ee-833b-10d5b4b29bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;Luas Lahan&quot; and @type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23f618dd-7aa5-4002-a30f-d88f42fd85b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Luas Lahan</value>
      <webElementGuid>4dcf41c5-7d4d-47fe-a54a-52852c2ed4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1886345e-ce20-4242-a8df-29aa8c7d362b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2100b126-2abf-43b4-8a0a-fde458c5cccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-18</value>
      <webElementGuid>6d179c90-097a-4266-9b6d-0fdd21b16034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-v-0-18-messages</value>
      <webElementGuid>29645d93-f6b4-4850-9cd2-65393c9df626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-18&quot;)</value>
      <webElementGuid>395bad6d-0815-4ddf-81e7-8c62d6ec1733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-v-0-18']</value>
      <webElementGuid>9aadcd16-2c61-4104-bb6c-1b962d894191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>a7386f2f-b5bb-4fc6-91ec-1ff7a125f28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Luas Lahan' and @type = 'text' and @id = 'input-v-0-18']</value>
      <webElementGuid>bc2c7bb0-8d52-497e-99e8-001ea54d7db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
