<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_M_input-v-0-26</name>
   <tag></tag>
   <elementGuidId>8eaed880-929c-4f66-91f7-ce378008810d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-v-0-26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-v-0-26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ca0b4d1-8eab-421a-8bb0-83c660937b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>2229d11f-a00a-4296-92f9-1e08fe80152b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat lengkap</value>
      <webElementGuid>94be044b-3731-4a13-997e-8622a46a65c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e718332d-3df9-471c-b0c3-1581b9c38062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-v-0-26</value>
      <webElementGuid>37004b20-70cc-4bb5-9b4d-c343ab112aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-v-0-26-messages</value>
      <webElementGuid>81644d01-d081-4784-870e-2cb6b3b7e3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-v-0-26&quot;)</value>
      <webElementGuid>f882c5ee-2dc5-423b-8f5e-6b0237eb0a69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-v-0-26']</value>
      <webElementGuid>ac02e409-dfe9-4dd5-af0e-3cde17155ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8eb8755c-7d2b-4809-880d-0d2eda49e48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Alamat lengkap' and @id = 'input-v-0-26']</value>
      <webElementGuid>67ba985e-efa0-4f09-8f36-6284e8d9484a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
